project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!STYLING.md"

execute:
  freeze: auto

website:
  title: "tidymodels"
  navbar:
    pinned: true
    right:
      - text: "Packages"
        href: packages/index.qmd
      - text: "Get Started"
        href: start/index.qmd
      - text: "Learn"
        href: learn/index.qmd
      - text: "Help"
        href: help/index.qmd
      - text: "Contribute"
        href: contribute/index.qmd
      - text: "About"
        href: about/index.qmd
      - text: "Find"
        href: find/index.qmd
      - icon: github
        href: https://github.com/tidymodels/
        aria-label: GitHub

  sidebar:
    - id: get-started
      style: "floating"
      contents:
        - text: "GET STARTED"
          href: start/index.qmd
        - text: "Build a model"
          href: start/models/index.qmd
        - text: "Preprocess your data with recipes"
          href: start/recipes/index.qmd
        - text: "Evaluate your model with resamples"
          href: start/resampling/index.qmd
        - text: "Tune model parameters"
          href: start/tuning/index.qmd
        - text: "A predictive modeling case study"
          href: start/case-study/index.qmd
    - id: learn
      collapse-level: 1
      contents:
        - text: "Learn"
          href: learn/index.qmd
        - section: "Perform Statistical Analyses"
          contents:
            - learn/statistics/bootstrap/index.qmd
            - learn/statistics/infer/index.qmd
            - learn/statistics/k-means/index.qmd
            - learn/statistics/tidy-analysis/index.qmd
            - learn/statistics/xtabs/index.qmd
        - section: "Create Robust Models"
          contents:
            - learn/models/coefficients/index.qmd
            - learn/models/parsnip-nnet/index.qmd
            - learn/models/parsnip-ranger-glmnet/index.qmd
            - learn/models/pls/index.qmd
            - learn/models/sub-sampling/index.qmd
            - learn/models/time-series/index.qmd
        - section: "Develop custom modeling tools"
          contents:
            - learn/develop/broom/index.qmd
            - learn/develop/metrics/index.qmd
            - learn/develop/models/index.qmd
            - learn/develop/parameters/index.qmd
            - learn/develop/recipes/index.qmd
        - section: "Tune, compare, and work with your models"
          contents:
            - learn/work/bayes-opt/index.qmd
            - learn/work/case-weights/index.qmd
            - learn/work/nested-resampling/index.qmd
            - learn/work/tune-svm/index.qmd
            - learn/work/tune-text/index.qmd

  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    right: |
      <a onclick="window.scrollTo({ top: 0, behavior: 'smooth' }); return false;" role="button">
         {{< fa chevron-up >}}
      </a>
  repo-url: https://github.com/tidymodels/tidymodels_dot_org
  repo-actions: [edit, issue]

format:
  html:
    quarto-required: ">= 1.3.353"
    toc: true
    linestretch: 1.6
    grid:
      body-width: 840px

theme:
  - cosmo
  - styles.scss
  - styles-frontpage.scss
