---
title: "Search all of tidymodels"
disable_jquery: true
weight: 1
---

```{r ex_setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  digits = 3,
  collapse = TRUE,
  comment = "#>"
  )
options(digits = 3)
script <- here::here("static/code/get_pkgdown_urls.R")
source(script)
library(DT)
```


In the searchable table below, you'll find all the functions available in the [tidymodels packages](/packages/). The first column called **topic** provides a link to the function's reference page on each package's documentation site.

<br>

```{r table-compute, include = FALSE}
pkgs <- c("broom", "butcher", "corrr", "dials", "discrim", 
          "embed", "hardhat", "infer", "modeldata", "modeldb", "parsnip", 
          "probably", "recipes", "rsample", "textrecipes", "tidyposterior", 
          "tidypredict", "yardstick", "workflows")
pkg_urls <- get_pkgdown_urls(pkgs)
```


```{r table-display, echo = FALSE}
pkg_urls %>% 
  mutate(package = as.factor(package)) %>% 
  datatable(rownames = FALSE,
            class = 'cell-border stripe',
            filter = 'top',
            escape = FALSE,
            options = list(pageLength = 5))
```





