{
  "hash": "675316c530c826b8fab7e6e90401247f",
  "result": {
    "markdown": "---\ntitle: \"Nested resampling\"\ncategories:\n  - nested resampling\n  - SVMs\ntype: learn-subsection\nweight: 2\ndescription: | \n  Estimate the best hyperparameters for a model using nested resampling.\ntoc: true\ntoc-depth: 2\ninclude-after-body: ../../../resources.html\n---\n\n\n\n\n\n\n## Introduction\n\nTo use code in this article,  you will need to install the following packages: furrr, kernlab, mlbench, scales, and tidymodels.\n\nIn this article, we discuss an alternative method for evaluating and tuning models, called [nested resampling](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C7&q=%22nested+resampling%22+inner+outer&btnG=). While it is more computationally taxing and challenging to implement than other resampling methods, it has the potential to produce better estimates of model performance.\n\n## Resampling models\n\nA typical scheme for splitting the data when developing a predictive model is to create an initial split of the data into a training and test set. If resampling is used, it is executed on the training set. A series of binary splits is created. In rsample, we use the term *analysis set* for the data that are used to fit the model and the term *assessment set* for the set used to compute performance:\n\n\n::: {.cell layout-align=\"center\" hash='cache/resampling-fig_214078c494ebc8f5e36f063603746f5e'}\n::: {.cell-output-display}\n![](img/resampling.svg){fig-align='center' width=70%}\n:::\n:::\n\n\nA common method for tuning models is [grid search](/learn/work/tune-svm/) where a candidate set of tuning parameters is created. The full set of models for every combination of the tuning parameter grid and the resamples is fitted. Each time, the assessment data are used to measure performance and the average value is determined for each tuning parameter.\n\nThe potential problem is that once we pick the tuning parameter associated with the best performance, this performance value is usually quoted as the performance of the model. There is serious potential for *optimization bias* since we use the same data to tune the model and to assess performance. This would result in an optimistic estimate of performance.\n\nNested resampling uses an additional layer of resampling that separates the tuning activities from the process used to estimate the efficacy of the model. An *outer* resampling scheme is used and, for every split in the outer resample, another full set of resampling splits are created on the original analysis set. For example, if 10-fold cross-validation is used on the outside and 5-fold cross-validation on the inside, a total of 500 models will be fit. The parameter tuning will be conducted 10 times and the best parameters are determined from the average of the 5 assessment sets. This process occurs 10 times.\n\nOnce the tuning results are complete, a model is fit to each of the outer resampling splits using the best parameter associated with that resample. The average of the outer method's assessment sets are a unbiased estimate of the model.\n\nWe will simulate some regression data to illustrate the methods. The mlbench package has a function `mlbench::mlbench.friedman1()` that can simulate a complex regression data structure from the [original MARS publication](https://scholar.google.com/scholar?hl=en&q=%22Multivariate+adaptive+regression+splines%22&btnG=&as_sdt=1%2C7&as_sdtp=). A training set size of 100 data points are generated as well as a large set that will be used to characterize how well the resampling procedure performed.\n\n\n::: {.cell layout-align=\"center\" hash='cache/sim-data_e983661ec506849cbf1bd8ec69ce0743'}\n\n```{.r .cell-code}\nlibrary(mlbench)\nsim_data <- function(n) {\n  tmp <- mlbench.friedman1(n, sd = 1)\n  tmp <- cbind(tmp$x, tmp$y)\n  tmp <- as.data.frame(tmp)\n  names(tmp)[ncol(tmp)] <- \"y\"\n  tmp\n}\n\nset.seed(9815)\ntrain_dat <- sim_data(100)\nlarge_dat <- sim_data(10^5)\n```\n:::\n\n\n## Nested resampling\n\nTo get started, the types of resampling methods need to be specified. This isn't a large data set, so 5 repeats of 10-fold cross validation will be used as the *outer* resampling method for generating the estimate of overall performance. To tune the model, it would be good to have precise estimates for each of the values of the tuning parameter so let's use 25 iterations of the bootstrap. This means that there will eventually be `5 * 10 * 25 = 1250` models that are fit to the data *per tuning parameter*. These models will be discarded once the performance of the model has been quantified.\n\nTo create the tibble with the resampling specifications:\n\n\n::: {.cell layout-align=\"center\" hash='cache/tibble-gen_ed46b63d3ba7bc40ee23e6405c95dba4'}\n\n```{.r .cell-code}\nlibrary(tidymodels)\nresults <- nested_cv(train_dat, \n                     outside = vfold_cv(repeats = 5), \n                     inside = bootstraps(times = 25))\nresults\n#> # Nested resampling:\n#> #  outer: 10-fold cross-validation repeated 5 times\n#> #  inner: Bootstrap sampling\n#> # A tibble: 50 × 4\n#>    splits          id      id2    inner_resamples\n#>    <list>          <chr>   <chr>  <list>         \n#>  1 <split [90/10]> Repeat1 Fold01 <boot [25 × 2]>\n#>  2 <split [90/10]> Repeat1 Fold02 <boot [25 × 2]>\n#>  3 <split [90/10]> Repeat1 Fold03 <boot [25 × 2]>\n#>  4 <split [90/10]> Repeat1 Fold04 <boot [25 × 2]>\n#>  5 <split [90/10]> Repeat1 Fold05 <boot [25 × 2]>\n#>  6 <split [90/10]> Repeat1 Fold06 <boot [25 × 2]>\n#>  7 <split [90/10]> Repeat1 Fold07 <boot [25 × 2]>\n#>  8 <split [90/10]> Repeat1 Fold08 <boot [25 × 2]>\n#>  9 <split [90/10]> Repeat1 Fold09 <boot [25 × 2]>\n#> 10 <split [90/10]> Repeat1 Fold10 <boot [25 × 2]>\n#> # ℹ 40 more rows\n```\n:::\n\n\nThe splitting information for each resample is contained in the `split` objects. Focusing on the second fold of the first repeat:\n\n\n::: {.cell layout-align=\"center\" hash='cache/split-example_730f1d4661d7d82e99e7ae9d90d96252'}\n\n```{.r .cell-code}\nresults$splits[[2]]\n#> <Analysis/Assess/Total>\n#> <90/10/100>\n```\n:::\n\n\n`<90/10/100>` indicates the number of observations in the analysis set, assessment set, and the original data.\n\nEach element of `inner_resamples` has its own tibble with the bootstrapping splits.\n\n\n::: {.cell layout-align=\"center\" hash='cache/inner-splits_0546fa38a72ce1afdce4680dececa5d8'}\n\n```{.r .cell-code}\nresults$inner_resamples[[5]]\n#> # Bootstrap sampling \n#> # A tibble: 25 × 2\n#>    splits          id         \n#>    <list>          <chr>      \n#>  1 <split [90/31]> Bootstrap01\n#>  2 <split [90/33]> Bootstrap02\n#>  3 <split [90/37]> Bootstrap03\n#>  4 <split [90/31]> Bootstrap04\n#>  5 <split [90/32]> Bootstrap05\n#>  6 <split [90/32]> Bootstrap06\n#>  7 <split [90/36]> Bootstrap07\n#>  8 <split [90/34]> Bootstrap08\n#>  9 <split [90/29]> Bootstrap09\n#> 10 <split [90/31]> Bootstrap10\n#> # ℹ 15 more rows\n```\n:::\n\n\nThese are self-contained, meaning that the bootstrap sample is aware that it is a sample of a specific 90% of the data:\n\n\n::: {.cell layout-align=\"center\" hash='cache/inner-boot-split_d614aafea425464b013e25aa1e7fda68'}\n\n```{.r .cell-code}\nresults$inner_resamples[[5]]$splits[[1]]\n#> <Analysis/Assess/Total>\n#> <90/31/90>\n```\n:::\n\n\nTo start, we need to define how the model will be created and measured. Let's use a radial basis support vector machine model via the function `kernlab::ksvm`. This model is generally considered to have *two* tuning parameters: the SVM cost value and the kernel parameter `sigma`. For illustration purposes here, only the cost value will be tuned and the function `kernlab::sigest` will be used to estimate `sigma` during each model fit. This is automatically done by `ksvm`.\n\nAfter the model is fit to the analysis set, the root-mean squared error (RMSE) is computed on the assessment set. **One important note:** for this model, it is critical to center and scale the predictors before computing dot products. We don't do this operation here because `mlbench.friedman1` simulates all of the predictors to be standardized uniform random variables.\n\nOur function to fit the model and compute the RMSE is:\n\n\n::: {.cell layout-align=\"center\" hash='cache/rmse-func_234730528ec8a0043f8c594c31abc649'}\n\n```{.r .cell-code}\nlibrary(kernlab)\n\n# `object` will be an `rsplit` object from our `results` tibble\n# `cost` is the tuning parameter\nsvm_rmse <- function(object, cost = 1) {\n  y_col <- ncol(object$data)\n  mod <- \n    svm_rbf(mode = \"regression\", cost = cost) %>% \n    set_engine(\"kernlab\") %>% \n    fit(y ~ ., data = analysis(object))\n  \n  holdout_pred <- \n    predict(mod, assessment(object) %>% dplyr::select(-y)) %>% \n    bind_cols(assessment(object) %>% dplyr::select(y))\n  rmse(holdout_pred, truth = y, estimate = .pred)$.estimate\n}\n\n# In some case, we want to parameterize the function over the tuning parameter:\nrmse_wrapper <- function(cost, object) svm_rmse(object, cost)\n```\n:::\n\n\nFor the nested resampling, a model needs to be fit for each tuning parameter and each bootstrap split. To do this, create a wrapper:\n\n\n::: {.cell layout-align=\"center\" hash='cache/inner-tune-func_5699d21fd6e91cb7f1d70c07e072bc52'}\n\n```{.r .cell-code}\n# `object` will be an `rsplit` object for the bootstrap samples\ntune_over_cost <- function(object) {\n  tibble(cost = 2 ^ seq(-2, 8, by = 1)) %>% \n    mutate(RMSE = map_dbl(cost, rmse_wrapper, object = object))\n}\n```\n:::\n\n\nSince this will be called across the set of outer cross-validation splits, another wrapper is required:\n\n\n::: {.cell layout-align=\"center\" hash='cache/inner-func_e60f5a82560824dd74fe7a4086f7668e'}\n\n```{.r .cell-code}\n# `object` is an `rsplit` object in `results$inner_resamples` \nsummarize_tune_results <- function(object) {\n  # Return row-bound tibble that has the 25 bootstrap results\n  map_df(object$splits, tune_over_cost) %>%\n    # For each value of the tuning parameter, compute the \n    # average RMSE which is the inner bootstrap estimate. \n    group_by(cost) %>%\n    summarize(mean_RMSE = mean(RMSE, na.rm = TRUE),\n              n = length(RMSE),\n              .groups = \"drop\")\n}\n```\n:::\n\n\nNow that those functions are defined, we can execute all the inner resampling loops:\n\n\n::: {.cell layout-align=\"center\" hash='cache/inner-runs_ca610ccb577b23142f8afd7cda95089e'}\n\n```{.r .cell-code}\ntuning_results <- map(results$inner_resamples, summarize_tune_results) \n```\n:::\n\n\nAlternatively, since these computations can be run in parallel, we can use the furrr package. Instead of using `map()`, the function `future_map()` parallelizes the iterations using the [future package](https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html). The `multisession` plan uses the local cores to process the inner resampling loop. The end results are the same as the sequential computations.\n\n\n::: {.cell layout-align=\"center\" hash='cache/inner-runs-parallel_0e2e84113b39b62daa49eaad97238ac6'}\n\n```{.r .cell-code}\nlibrary(furrr)\nplan(multisession)\n\ntuning_results <- future_map(results$inner_resamples, summarize_tune_results) \n```\n:::\n\n\nThe object `tuning_results` is a list of data frames for each of the 50 outer resamples.\n\nLet's make a plot of the averaged results to see what the relationship is between the RMSE and the tuning parameters for each of the inner bootstrapping operations:\n\n\n::: {.cell layout-align=\"center\" hash='cache/rmse-plot_47c97acb3c9e2590f03f265dcd2dd865'}\n\n```{.r .cell-code}\nlibrary(scales)\n\npooled_inner <- tuning_results %>% bind_rows\n\nbest_cost <- function(dat) dat[which.min(dat$mean_RMSE),]\n\np <- \n  ggplot(pooled_inner, aes(x = cost, y = mean_RMSE)) + \n  scale_x_continuous(trans = 'log2') +\n  xlab(\"SVM Cost\") + ylab(\"Inner RMSE\")\n\nfor (i in 1:length(tuning_results))\n  p <- p  +\n  geom_line(data = tuning_results[[i]], alpha = .2) +\n  geom_point(data = best_cost(tuning_results[[i]]), pch = 16, alpha = 3/4)\n\np <- p + geom_smooth(data = pooled_inner, se = FALSE)\np\n```\n\n::: {.cell-output-display}\n![](figs/rmse-plot-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\nEach gray line is a separate bootstrap resampling curve created from a different 90% of the data. The blue line is a LOESS smooth of all the results pooled together.\n\nTo determine the best parameter estimate for each of the outer resampling iterations:\n\n\n::: {.cell layout-align=\"center\" hash='cache/choose_16a9265675bde0043286c8a94fcd67a9'}\n\n```{.r .cell-code}\ncost_vals <- \n  tuning_results %>% \n  map_df(best_cost) %>% \n  select(cost)\n\nresults <- \n  bind_cols(results, cost_vals) %>% \n  mutate(cost = factor(cost, levels = paste(2 ^ seq(-2, 8, by = 1))))\n\nggplot(results, aes(x = cost)) + \n  geom_bar() + \n  xlab(\"SVM Cost\") + \n  scale_x_discrete(drop = FALSE)\n```\n\n::: {.cell-output-display}\n![](figs/choose-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\nMost of the resamples produced an optimal cost value of 2.0, but the distribution is right-skewed due to the flat trend in the resampling profile once the cost value becomes 10 or larger.\n\nNow that we have these estimates, we can compute the outer resampling results for each of the 50 splits using the corresponding tuning parameter value:\n\n\n::: {.cell layout-align=\"center\" hash='cache/run-out-r_4763ba770361039f73c24636628bc34f'}\n\n```{.r .cell-code}\nresults <- \n  results %>% \n  mutate(RMSE = map2_dbl(splits, cost, svm_rmse))\n\nsummary(results$RMSE)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>   1.672   2.095   2.685   2.690   3.252   4.254\n```\n:::\n\n\nThe estimated RMSE for the model tuning process is 2.69.\n\nWhat is the RMSE estimate for the non-nested procedure when only the outer resampling method is used? For each cost value in the tuning grid, 50 SVM models are fit and their RMSE values are averaged. The table of cost values and mean RMSE estimates is used to determine the best cost value. The associated RMSE is the biased estimate.\n\n\n::: {.cell layout-align=\"center\" hash='cache/not-nested_352b1fd09cc9828e5d75a4c8d1abc6bf'}\n\n```{.r .cell-code}\nnot_nested <- \n  map(results$splits, tune_over_cost) %>%\n  bind_rows\n\nouter_summary <- not_nested %>% \n  group_by(cost) %>% \n  summarize(outer_RMSE = mean(RMSE), n = length(RMSE))\n\nouter_summary\n#> # A tibble: 11 × 3\n#>      cost outer_RMSE     n\n#>     <dbl>      <dbl> <int>\n#>  1   0.25       3.54    50\n#>  2   0.5        3.11    50\n#>  3   1          2.77    50\n#>  4   2          2.62    50\n#>  5   4          2.65    50\n#>  6   8          2.75    50\n#>  7  16          2.82    50\n#>  8  32          2.82    50\n#>  9  64          2.83    50\n#> 10 128          2.83    50\n#> 11 256          2.82    50\n\nggplot(outer_summary, aes(x = cost, y = outer_RMSE)) + \n  geom_point() + \n  geom_line() + \n  scale_x_continuous(trans = 'log2') +\n  xlab(\"SVM Cost\") + ylab(\"RMSE\")\n```\n\n::: {.cell-output-display}\n![](figs/not-nested-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\nThe non-nested procedure estimates the RMSE to be 2.62. Both estimates are fairly close.\n\nThe approximately true RMSE for an SVM model with a cost value of 2.0 can be approximated with the large sample that was simulated at the beginning.\n\n\n::: {.cell layout-align=\"center\" hash='cache/large-sample-estimate_e753225c1e50dcca8f214f4e41cc47bd'}\n\n```{.r .cell-code}\nfinalModel <- ksvm(y ~ ., data = train_dat, C = 2)\nlarge_pred <- predict(finalModel, large_dat[, -ncol(large_dat)])\nsqrt(mean((large_dat$y - large_pred) ^ 2, na.rm = TRUE))\n#> [1] 2.712059\n```\n:::\n\n\nThe nested procedure produces a closer estimate to the approximate truth but the non-nested estimate is very similar.\n\n## Session information {#session-info}\n\n\n::: {.cell layout-align=\"center\" hash='cache/si_43a75b68dcc94565ba13180d7ad26a69'}\n\n```\n#> ─ Session info ─────────────────────────────────────────────────────\n#>  setting  value\n#>  version  R version 4.3.0 (2023-04-21)\n#>  os       macOS Monterey 12.6\n#>  system   aarch64, darwin20\n#>  ui       X11\n#>  language (EN)\n#>  collate  en_US.UTF-8\n#>  ctype    en_US.UTF-8\n#>  tz       America/Los_Angeles\n#>  date     2023-05-25\n#>  pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)\n#> \n#> ─ Packages ─────────────────────────────────────────────────────────\n#>  package    * version date (UTC) lib source\n#>  broom      * 1.0.4   2023-03-11 [1] CRAN (R 4.3.0)\n#>  dials      * 1.2.0   2023-04-03 [1] CRAN (R 4.3.0)\n#>  dplyr      * 1.1.2   2023-04-20 [1] CRAN (R 4.3.0)\n#>  furrr      * 0.3.1   2022-08-15 [1] CRAN (R 4.3.0)\n#>  ggplot2    * 3.4.2   2023-04-03 [1] CRAN (R 4.3.0)\n#>  infer      * 1.0.4   2022-12-02 [1] CRAN (R 4.3.0)\n#>  kernlab    * 0.9-32  2023-01-31 [1] CRAN (R 4.3.0)\n#>  mlbench    * 2.1-3.1 2023-05-05 [1] CRAN (R 4.3.0)\n#>  parsnip    * 1.1.0   2023-04-12 [1] CRAN (R 4.3.0)\n#>  purrr      * 1.0.1   2023-01-10 [1] CRAN (R 4.3.0)\n#>  recipes    * 1.0.6   2023-04-25 [1] CRAN (R 4.3.0)\n#>  rlang        1.1.1   2023-04-28 [1] CRAN (R 4.3.0)\n#>  rsample    * 1.1.1   2022-12-07 [1] CRAN (R 4.3.0)\n#>  scales     * 1.2.1   2022-08-20 [1] CRAN (R 4.3.0)\n#>  tibble     * 3.2.1   2023-03-20 [1] CRAN (R 4.3.0)\n#>  tidymodels * 1.1.0   2023-05-01 [1] CRAN (R 4.3.0)\n#>  tune       * 1.1.1   2023-04-11 [1] CRAN (R 4.3.0)\n#>  workflows  * 1.1.3   2023-02-22 [1] CRAN (R 4.3.0)\n#>  yardstick  * 1.2.0   2023-04-21 [1] CRAN (R 4.3.0)\n#> \n#>  [1] /Users/emilhvitfeldt/Library/R/arm64/4.3/library\n#>  [2] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library\n#> \n#> ────────────────────────────────────────────────────────────────────\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}