---
title: "Search all of tidymodels"
disable_jquery: true
weight: 1
---

```{r ex_setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  digits = 3,
  collapse = TRUE,
  comment = "#>"
  )
options(digits = 3)
script <- here::here("static/code/get_pkgdown_urls.R")
source(script)
library(DT)
```


Here are all the functions available across all of the [tidymodels packages](/packages/). Click on the link in the **topic** column to find the relevant reference documentation.

<br>

```{r table-compute, include = FALSE}
pkgs <- c("applicable", "baguette", "broom", "butcher", 
          "corrr", "dials", "discrim", 
          "embed", "finetune", "hardhat", "infer", "modeldata", "modeldb", 
          "multilevelmod", "parsnip", "plsmod",
          "poissonreg", "probably", "recipes", "rsample", "spatialsample", 
          "textrecipes", "tidypredict", "tune", "yardstick", 
          "usemodels", "workflows", "workflowsets")
pkgs <- tibble(pkg = pkgs, 
               base_url = paste0("https://", pkg, ".tidymodels.org/")) 

pkg_urls <- get_pkgdown_urls(pkgs) %>% 
  select(title, topic, package)
```


```{r table-display, echo = FALSE}
pkg_urls %>% 
  mutate(package = as.factor(package)) %>% 
  datatable(rownames = FALSE,
            class = 'cell-border stripe',
            filter = 'top',
            escape = FALSE,
            options = list(pageLength = 5))
```





