---
title: "Resampling a model"
weight: 3
tags: [Bayesian analysis, regression models]
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<p>Once we have a model trained, we need a way to measure how well that model is doing. This tutorial explains how to characterize model performance based on <strong>resampling</strong> statistics. It requires that you have the following packages installed: <code>modeldata</code>, <code>ranger</code>, and <code>tidymodels</code>.</p>
<div id="predicting-image-segmentation" class="section level2">
<h2>Predicting image segmentation</h2>
<p>Some biologists conduct experiments on cells. In drug discovery, a particular type of cell can be treated with either a drug or control and then observed to see what the effect is (if any). A common approach for this kind of measurement is cell imaging. Different parts of the cells can be colored so that the locations of a cell can be determined.</p>
<p>For example, in top panel of this image of five cells, the green color is meant to define the boundary of the cell (coloring something called the cytoskeleton) while the blue color defines the nucleus of the cell.</p>
<p><img src="/Users/alison/rsites/tidymodels.org/static/images/cells.png" width="242" style="display: block; margin: auto;" /></p>
<p>Using these colors, the cells in an image can be <em>segmented</em> so that we know which pixels belong to which cell. If this is done well, the cell can be measured in different ways that are important to the biology. Sometimes the shape of the cell matters and different mathematical tools are used to summarize characteristics like the size or “oblongness” of the cell.</p>
<p>The bottom panel shows some segmentation results. Cells 1 and 5 are fairly well segmented. However, cells 2 to 4 are bunched up together because the segmentation was not very good. The consequence of bad segmentation is data contamination; when the biologist analyzes the shape or size of these cells, the data are inaccurate and could lead to the wrong conclusion.</p>
<p>A cell-based experiment might involve millions of cells so it is unfeasible to visually assessment all. Instead, a subsample can be created and the cells can be manually labeled by experts as either poorly segmented (<code>PS</code>) or well-segmented (<code>WS</code>). If we can predict these labels accurately, the larger data set can be improved by filtering out the cells most likely to be poorly segmented.</p>
<p>An example data set called <code>cells</code> is contained in the <code>modeldata</code> package. It has labeled data for 2019 cells. Each also has a total of 56 predictors based on automated image analysis measurements. For example, <code>avg_inten_ch_1</code> is the mean intensity of the data contained in the nucleus, <code>area_ch_1</code> is the total size of the cell, and so on (some predictors are fairly arcane in nature).</p>
<pre class="r"><code>data(cells, package = &quot;modeldata&quot;)
cells</code></pre>
<pre><code>#&gt; # A tibble: 2,019 x 58
#&gt;    case  class angle_ch_1 area_ch_1 avg_inten_ch_1 avg_inten_ch_2 avg_inten_ch_3 avg_inten_ch_4
#&gt;    &lt;fct&gt; &lt;fct&gt;      &lt;dbl&gt;     &lt;int&gt;          &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
#&gt;  1 Test  PS        143.         185           15.7           4.95           9.55           2.21
#&gt;  2 Train PS        134.         819           31.9         207.            69.9          164.  
#&gt;  3 Train WS        107.         431           28.0         116.            63.9          107.  
#&gt;  4 Train PS         69.2        298           19.5         102.            28.2           31.0 
#&gt;  5 Test  PS          2.89       285           24.3         112.            20.5           40.6 
#&gt;  6 Test  WS         40.7        172          326.          654.           129.           347.  
#&gt;  7 Test  WS        174.         177          260.          596.           124.           273.  
#&gt;  8 Test  PS        180.         251           18.3           5.73          17.2            1.55
#&gt;  9 Test  WS         18.9        495           16.1          89.5           13.7           51.4 
#&gt; 10 Test  WS        153.         384           17.7          89.9           20.4           63.1 
#&gt; # … with 2,009 more rows, and 50 more variables: convex_hull_area_ratio_ch_1 &lt;dbl&gt;,
#&gt; #   convex_hull_perim_ratio_ch_1 &lt;dbl&gt;, diff_inten_density_ch_1 &lt;dbl&gt;,
#&gt; #   diff_inten_density_ch_3 &lt;dbl&gt;, diff_inten_density_ch_4 &lt;dbl&gt;, entropy_inten_ch_1 &lt;dbl&gt;,
#&gt; #   entropy_inten_ch_3 &lt;dbl&gt;, entropy_inten_ch_4 &lt;dbl&gt;, eq_circ_diam_ch_1 &lt;dbl&gt;,
#&gt; #   eq_ellipse_lwr_ch_1 &lt;dbl&gt;, eq_ellipse_oblate_vol_ch_1 &lt;dbl&gt;, eq_ellipse_prolate_vol_ch_1 &lt;dbl&gt;,
#&gt; #   eq_sphere_area_ch_1 &lt;dbl&gt;, eq_sphere_vol_ch_1 &lt;dbl&gt;, fiber_align_2_ch_3 &lt;dbl&gt;,
#&gt; #   fiber_align_2_ch_4 &lt;dbl&gt;, fiber_length_ch_1 &lt;dbl&gt;, fiber_width_ch_1 &lt;dbl&gt;,
#&gt; #   inten_cooc_asm_ch_3 &lt;dbl&gt;, inten_cooc_asm_ch_4 &lt;dbl&gt;, inten_cooc_contrast_ch_3 &lt;dbl&gt;,
#&gt; #   inten_cooc_contrast_ch_4 &lt;dbl&gt;, inten_cooc_entropy_ch_3 &lt;dbl&gt;, inten_cooc_entropy_ch_4 &lt;dbl&gt;,
#&gt; #   inten_cooc_max_ch_3 &lt;dbl&gt;, inten_cooc_max_ch_4 &lt;dbl&gt;, kurt_inten_ch_1 &lt;dbl&gt;,
#&gt; #   kurt_inten_ch_3 &lt;dbl&gt;, kurt_inten_ch_4 &lt;dbl&gt;, length_ch_1 &lt;dbl&gt;, neighbor_avg_dist_ch_1 &lt;dbl&gt;,
#&gt; #   neighbor_min_dist_ch_1 &lt;dbl&gt;, neighbor_var_dist_ch_1 &lt;dbl&gt;, perim_ch_1 &lt;dbl&gt;,
#&gt; #   shape_bfr_ch_1 &lt;dbl&gt;, shape_lwr_ch_1 &lt;dbl&gt;, shape_p_2_a_ch_1 &lt;dbl&gt;, skew_inten_ch_1 &lt;dbl&gt;,
#&gt; #   skew_inten_ch_3 &lt;dbl&gt;, skew_inten_ch_4 &lt;dbl&gt;, spot_fiber_count_ch_3 &lt;int&gt;,
#&gt; #   spot_fiber_count_ch_4 &lt;dbl&gt;, total_inten_ch_1 &lt;int&gt;, total_inten_ch_2 &lt;dbl&gt;,
#&gt; #   total_inten_ch_3 &lt;int&gt;, total_inten_ch_4 &lt;int&gt;, var_inten_ch_1 &lt;dbl&gt;, var_inten_ch_3 &lt;dbl&gt;,
#&gt; #   var_inten_ch_4 &lt;dbl&gt;, width_ch_1 &lt;dbl&gt;</code></pre>
<p>The rates of the classes are somewhat imbalanced; there are more poorly segmented cells than well-segmented cells:</p>
<pre class="r"><code>class_rates &lt;- table(cells$class)/nrow(cells)
class_rates</code></pre>
<pre><code>#&gt; 
#&gt;    PS    WS 
#&gt; 0.644 0.356</code></pre>
</div>
<div id="data-splitting" class="section level2">
<h2>Data splitting</h2>
<p>When beginning a modeling project, it is common to <a href="https://bookdown.org/max/FES/data-splitting.html">separate the data set</a> into two partitions:</p>
<ul>
<li><p>The <em>training set</em> is used to estimate parameters, compare models and feature engineering techniques, tune models, etc.</p></li>
<li><p>The <em>test set</em> is held in reserve until the end of the project, at which point there should only be one or two models under serious consideration. It is used as an unbiased source for measuring final model performance.</p></li>
</ul>
<p>There are different ways to create these partitions of the data. The most common approach is to use a random sample. Suppose that one quarter of the data were reserved for the test set. Random sampling would randomly select 25% for the test set and use the remainder for the training set. We can use the <code>rsample</code> package for this purpose. In the original analysis, the authors made their own training/test set and that information is contained in the column <code>case</code>. To demonstrate how to make a split, we’ll remove this column before we make our own split.</p>
<p>Since random sampling uses random numbers, it is important to set the random number seed. This ensures that the random numbers can be reproduced at a later time (if needed).</p>
<p><code>rsample::initial_split()</code> takes the original data and saves the information on how to make the partitions. After that, the <code>training()</code> and <code>testing()</code> functions return the actual data sets:</p>
<pre class="r"><code>library(tidymodels) # Load the rsample package

set.seed(2369)
tr_te_split &lt;- initial_split(cells %&gt;% select(-case), prop = 3/4)
cell_train &lt;- training(tr_te_split)
cell_test  &lt;- testing(tr_te_split)

nrow(cell_train)</code></pre>
<pre><code>#&gt; [1] 1515</code></pre>
<pre class="r"><code>nrow(cell_train)/nrow(cells)</code></pre>
<pre><code>#&gt; [1] 0.75</code></pre>
<p>The majority of the modeling work is then conducted on the training set data.</p>
</div>
<div id="modeling" class="section level2">
<h2>Modeling</h2>
<p>Random forest models are ensembles of decisions trees. A large number of tree models are created for the ensemble based on slightly different versions of the training set. When creating the individual decision trees, the fitting process encourages then to be as diverse as possible. The collection of trees are combined into the random forest model and, when a new sample is predicted, the votes from each tree are used to calculate the final predicted value for the new sample.</p>
<p>This model is very low maintenance; it requires very little pre-processing of the data and, while it can be tuned, the default parameters tend to give reasonable results. At the same time, the number of trees in the ensemble should be large (in the thousands) and this makes the model moderately expensive to compute.</p>
<p>To fit a random forest model on the training set, use the <code>parsnip</code> package in conjunction with the <code>ranger</code> package. We first define the model that we want to create:</p>
<pre class="r"><code>rf_mod &lt;- 
  rand_forest(trees = 1000) %&gt;% 
  set_engine(&quot;ranger&quot;) %&gt;% 
  set_mode(&quot;classification&quot;)</code></pre>
<p>From this, the <code>fit()</code> function can be used with a simple model formula. Since random forest uses random numbers, we again set the seed prior to computing:</p>
<pre class="r"><code>set.seed(5273)
rf_fit &lt;- rf_mod %&gt;% fit(class ~ ., data = cell_train)
rf_fit</code></pre>
<pre><code>#&gt; parsnip model object
#&gt; 
#&gt; Fit time:  2.8s 
#&gt; Ranger result
#&gt; 
#&gt; Call:
#&gt;  ranger::ranger(formula = formula, data = data, num.trees = ~1000,      num.threads = 1, verbose = FALSE, seed = sample.int(10^5,          1), probability = TRUE) 
#&gt; 
#&gt; Type:                             Probability estimation 
#&gt; Number of trees:                  1000 
#&gt; Sample size:                      1515 
#&gt; Number of independent variables:  56 
#&gt; Mtry:                             7 
#&gt; Target node size:                 10 
#&gt; Variable importance mode:         none 
#&gt; Splitrule:                        gini 
#&gt; OOB prediction error (Brier s.):  0.123</code></pre>
</div>
<div id="estimating-performance" class="section level1">
<h1>Estimating performance</h1>
<p>In the course of any modeling project, we might create a variety of different models. To choose between them, we need to consider some performance statistics. In our example in this tutorial, we could compute:</p>
<ul>
<li><p>the area under the Receiver Operating Characteristic (ROC) curve, and</p></li>
<li><p>overall classification accuracy.</p></li>
</ul>
<p>The ROC curve uses the class probability estimates to give us a sense of performance across the entire set of potential probability cutoffs. Overall accuracy uses the hard class predictions to measure performance (assuming a simple 50% probability cutoff to categorize a cell as poorly segmented).</p>
<p>The <code>yardstick</code> package has functions for computing both of these measures called <code>roc_auc()</code> and <code>accuracy()</code>.</p>
<p>At first glance, it might seem like a good idea to use the training set data to compute these statistics<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. To do this, we call the <code>predict()</code> method to get both types of predictions (i.e. probabilities and hard class predictions).</p>
<pre class="r"><code>rf_training_pred &lt;- 
  predict(rf_fit, cell_train) %&gt;% 
  bind_cols(predict(rf_fit, cell_train, type = &quot;prob&quot;)) %&gt;% 
  # Add the true outcome data back in
  bind_cols(cell_train %&gt;% 
              select(class))</code></pre>
<p>Using the <code>yardstick</code> functions, this model has spectacular results, so spectacular that you might be starting to get suspicious:</p>
<pre class="r"><code>roc_auc(rf_training_pred,  truth = class, .pred_PS)</code></pre>
<pre><code>#&gt; # A tibble: 1 x 3
#&gt;   .metric .estimator .estimate
#&gt;   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
#&gt; 1 roc_auc binary          1.00</code></pre>
<pre class="r"><code>accuracy(rf_training_pred, truth = class, .pred_class)</code></pre>
<pre><code>#&gt; # A tibble: 1 x 3
#&gt;   .metric  .estimator .estimate
#&gt;   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
#&gt; 1 accuracy binary         0.992</code></pre>
<p>Now that we have this model with exceptional performance, we proceed to the test set. Unfortunately, we discover that, although our results aren’t bad, they are certainly worse than what we initially thought based on predicting the training set:</p>
<pre class="r"><code>rf_testing_pred &lt;- 
  predict(rf_fit, cell_test) %&gt;% 
  bind_cols(predict(rf_fit, cell_test, type = &quot;prob&quot;)) %&gt;% 
  bind_cols(cell_test %&gt;% select(class))

roc_auc(rf_testing_pred,  truth = class, .pred_PS)</code></pre>
<pre><code>#&gt; # A tibble: 1 x 3
#&gt;   .metric .estimator .estimate
#&gt;   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
#&gt; 1 roc_auc binary         0.916</code></pre>
<pre class="r"><code>accuracy(rf_testing_pred, truth = class, .pred_class)</code></pre>
<pre><code>#&gt; # A tibble: 1 x 3
#&gt;   .metric  .estimator .estimate
#&gt;   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
#&gt; 1 accuracy binary         0.835</code></pre>
<p><strong>What happened here?</strong></p>
<p>There are several reasons why training set statistics like the ones shown in this section can be unrealistically optimistic:</p>
<ul>
<li><p>Models like random forests, neural networks, and other black-box methods can essentially memorize the training set. Re-predicting that same set should always result in nearly perfect results<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>.</p></li>
<li><p>The training set does not have the capacity to be a good arbiter of performance. It is not an independent piece of information; predicting the training set can only reflect what the model already knows.</p></li>
</ul>
<p>To understand that second point better, think about an analogy from teaching. Suppose you give a class a test, then give them the answers, then provide the same test. The student scores on the <em>second</em> test do not accurately reflect what they know about the subject; these scores would probably be higher than their results on the first test.</p>
</div>
<div id="resampling-to-the-rescue" class="section level1">
<h1>Resampling to the rescue</h1>
<p>Resampling methods, such as cross-validation and the bootstrap, are empirical simulation systems. They create a series of data sets similar to the training/testing split discussed previously; a subset of the data are used for creating the model and a different subset is used to measure performance. Resampling is always used with the <em>training set</em>. This schematic from <a href="https://bookdown.org/max/FES/resampling.html">Kuhn and Johnson (2019)</a> illustrates data usage for resampling methods:</p>
<p><img src="/Users/alison/rsites/tidymodels.org/static/images/resampling.svg" width="70%" style="display: block; margin: auto;" /></p>
<p>Let’s use 10-fold cross-validation (CV) in this example. This method randomly allocates the 1515 cells in the training set to 10 groups of roughly equal size, called “folds”. For the first iteration of resampling, the first fold of about 151 cells are held out for the purpose of measuring performance. This is similar to a test set but, to avoid confusion, we call these data the <em>assessment set</em>. The other 90% of the data (about 1363 cells) are used to fit the model and is called the <em>analysis set</em>. This model is applied to the assessment set and performance statistics are computed on that assessment set.</p>
<p>In this example, 10-fold CV moves iteratively through the folds and leaves a different 10% out each time for model assessment. At the end of this process, there are 10 sets of performance statistics that were created on 10 data sets that were not used in the modeling process. For the cell example, this means 10 accuracies and 10 areas under the ROC curve. While 10 models were created, these are not used further; we do not keep the models themselves trained on these folds because their only purpose is calculating performance metrics.</p>
<p>The final resampling estimates for the model are the <strong>averages</strong> of the performance statistics replicates. For example, suppose for our data, the results were:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
resample
</th>
<th style="text-align:right;">
accuracy
</th>
<th style="text-align:right;">
roc_auc
</th>
<th style="text-align:right;">
assessment size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Fold01
</td>
<td style="text-align:right;">
0.822
</td>
<td style="text-align:right;">
0.890
</td>
<td style="text-align:right;">
152
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold02
</td>
<td style="text-align:right;">
0.836
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
152
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold03
</td>
<td style="text-align:right;">
0.829
</td>
<td style="text-align:right;">
0.913
</td>
<td style="text-align:right;">
152
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold04
</td>
<td style="text-align:right;">
0.803
</td>
<td style="text-align:right;">
0.902
</td>
<td style="text-align:right;">
152
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold05
</td>
<td style="text-align:right;">
0.836
</td>
<td style="text-align:right;">
0.901
</td>
<td style="text-align:right;">
152
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold06
</td>
<td style="text-align:right;">
0.801
</td>
<td style="text-align:right;">
0.874
</td>
<td style="text-align:right;">
151
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold07
</td>
<td style="text-align:right;">
0.815
</td>
<td style="text-align:right;">
0.919
</td>
<td style="text-align:right;">
151
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold08
</td>
<td style="text-align:right;">
0.801
</td>
<td style="text-align:right;">
0.886
</td>
<td style="text-align:right;">
151
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold09
</td>
<td style="text-align:right;">
0.788
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
151
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold10
</td>
<td style="text-align:right;">
0.874
</td>
<td style="text-align:right;">
0.930
</td>
<td style="text-align:right;">
151
</td>
</tr>
</tbody>
</table>
<p>From these resampling statistics, the final estimate of performance for this random forest model would be 0.902 for the area under the ROC curve and 0.82 for accuracy.</p>
<p>These resampling statistics are an effective method for measuring model performance <em>without</em> predicting the training set directly as a whole.</p>
<p>To generate these results, the first step is to create a resampling object using <code>rsample</code>. There are several resampling methods implemented and cross-validation folds can be created using <code>vfold_cv()</code>:</p>
<pre class="r"><code>set.seed(1697)
folds &lt;- vfold_cv(cell_train, v = 10)
folds</code></pre>
<pre><code>#&gt; #  10-fold cross-validation 
#&gt; # A tibble: 10 x 2
#&gt;    splits             id    
#&gt;    &lt;named list&gt;       &lt;chr&gt; 
#&gt;  1 &lt;split [1.4K/152]&gt; Fold01
#&gt;  2 &lt;split [1.4K/152]&gt; Fold02
#&gt;  3 &lt;split [1.4K/152]&gt; Fold03
#&gt;  4 &lt;split [1.4K/152]&gt; Fold04
#&gt;  5 &lt;split [1.4K/152]&gt; Fold05
#&gt;  6 &lt;split [1.4K/151]&gt; Fold06
#&gt;  7 &lt;split [1.4K/151]&gt; Fold07
#&gt;  8 &lt;split [1.4K/151]&gt; Fold08
#&gt;  9 &lt;split [1.4K/151]&gt; Fold09
#&gt; 10 &lt;split [1.4K/151]&gt; Fold10</code></pre>
<p>The list column for <code>splits</code> contains the information on which rows belong in the analysis and assessment sets. There are functions that can be used to extract the individual resampled data called <code>analysis()</code> and <code>assessment()</code>.</p>
<p>However, the <code>tune</code> package contains high-level functions that can do the required computations to resample a model (and, optionally, a recipe) for the purpose of measuring performance. The syntax is very similar to <code>fit()</code>:</p>
<pre class="r"><code>set.seed(5273)
rf_fit_rs &lt;- rf_mod %&gt;% 
  fit_resamples(class ~ ., folds)</code></pre>
<pre class="r"><code>rf_fit_rs</code></pre>
<pre><code>#&gt; #  10-fold cross-validation 
#&gt; # A tibble: 10 x 4
#&gt;    splits             id     .metrics         .notes          
#&gt;  * &lt;list&gt;             &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;          
#&gt;  1 &lt;split [1.4K/152]&gt; Fold01 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt;  2 &lt;split [1.4K/152]&gt; Fold02 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt;  3 &lt;split [1.4K/152]&gt; Fold03 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt;  4 &lt;split [1.4K/152]&gt; Fold04 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt;  5 &lt;split [1.4K/152]&gt; Fold05 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt;  6 &lt;split [1.4K/151]&gt; Fold06 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt;  7 &lt;split [1.4K/151]&gt; Fold07 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt;  8 &lt;split [1.4K/151]&gt; Fold08 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt;  9 &lt;split [1.4K/151]&gt; Fold09 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;
#&gt; 10 &lt;split [1.4K/151]&gt; Fold10 &lt;tibble [2 × 3]&gt; &lt;tibble [0 × 1]&gt;</code></pre>
<p>The results are similar to the <code>folds</code> results with some extra columns. The column <code>.metrics</code> contains the performance statistics created from the 10 assessment sets. These can be manually unnested but <code>tune</code> contains a number of simple functions that can extract these data:</p>
<pre class="r"><code>collect_metrics(rf_fit_rs)</code></pre>
<pre><code>#&gt; # A tibble: 2 x 5
#&gt;   .metric  .estimator  mean     n std_err
#&gt;   &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
#&gt; 1 accuracy binary     0.820    10 0.00785
#&gt; 2 roc_auc  binary     0.902    10 0.00519</code></pre>
<p>Think about these values we now have for accuracy and AUC. These performance metrics are now more realistic (i.e. lower) than our ill-advised first attempt at computing performance metrics in the section above. If we wanted to try different model types for this data set, we could more confidently compare performance metrics computed using resampling to choose between models. Also, remember that at the end of our project, we return to our test set to estimate final model performance. We have looked at this once already before we started using resampling, but let’s remind ourselves of the results:</p>
<pre class="r"><code>accuracy(rf_testing_pred, truth = class, .pred_class)</code></pre>
<pre><code>#&gt; # A tibble: 1 x 3
#&gt;   .metric  .estimator .estimate
#&gt;   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
#&gt; 1 accuracy binary         0.835</code></pre>
<pre class="r"><code>roc_auc(rf_testing_pred,  truth = class, .pred_PS)</code></pre>
<pre><code>#&gt; # A tibble: 1 x 3
#&gt;   .metric .estimator .estimate
#&gt;   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
#&gt; 1 roc_auc binary         0.916</code></pre>
<p>The performance metrics from the test set are much closer to the performance metrics computed using resampling than our first (“bad idea”) attempt. Resampling allows us to simulate how well our model will perform on new data, and the test set acts as the final, unbiased check for our model’s performance.</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Spoiler alert: it is a very bad idea to do this.<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Notice that this means our degree of optimism in training set statistics is model dependent.<a href="#fnref2" class="footnote-back">↩</a></p></li>
</ol>
</div>
