---
title: "List of all functions across packages"
disable_jquery: true
---

```{r ex_setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  digits = 3,
  collapse = TRUE,
  comment = "#>"
  )
options(digits = 3)
script <- here::here("static/code/get_pkgdown_urls.R")
source(script)
library(DT)
```


This table lists the functions in CRAN versions of the tidymodels packages. 

```{r table-compute, include = FALSE}
pkgs <- c("broom", "butcher", "corrr", "dials", "discrim", 
          "embed", "hardhat", "infer", "modeldata", "modeldb", "parsnip", 
          "probably", "recipes", "rsample", "textrecipes", "tidyposterior", 
          "tidypredict", "yardstick", "workflows")
pkg_urls <- get_pkgdown_urls(pkgs)
```

# Empty?

```{r table-display, echo = FALSE}
pkg_urls %>% 
      datatable(rownames = FALSE,
              class = 'cell-border stripe',
              filter = list(position = 'top'),
              options = list(autoWidth = TRUE,
                             bInfo = FALSE,
                             paging = TRUE),
              escape = FALSE)
```





